#IMPORT DATASET

In [0]:
import pandas

#READ THE DATA

In [0]:
data = pandas.read_csv('news.csv')

#CHECK THE NULL VALUES AND REMOVE IT IF ANY

In [3]:
data.isnull().values.any()

False

In [0]:
nan_rows = data[data['body'].isnull()]

#USE COUNT VECTORIZER FOR DATA PRE-PROCESSING YOU CAN USE TDF-ID VECTORIZER BASES ON YOUR NEED

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(stop_words='english')
dtm = cv.fit_transform(data['body'])

In [6]:
dtm

<389x13263 sparse matrix of type '<class 'numpy.int64'>'
	with 66083 stored elements in Compressed Sparse Row format>

#USE LDA FOR TOPIC MODELLING

In [0]:
from sklearn.decomposition import LatentDirichletAllocation

In [0]:
LDA = LatentDirichletAllocation(n_components=7)

In [9]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=None,
                          topic_word_prior=None, total_samples=1000000.0,
                          verbose=0)

#LETS PLAY WITH CV AND LDA TO KNOW MORE ABOUT THE DATA

In [10]:
len(cv.get_feature_names())
type(cv.get_feature_names())

list

In [11]:
cv.get_feature_names()

['00',
 '000',
 '004',
 '0059',
 '008',
 '01',
 '012',
 '013bipffpb',
 '014',
 '019',
 '02',
 '0202',
 '0212',
 '03',
 '036',
 '045',
 '05',
 '06',
 '060',
 '07',
 '076',
 '08',
 '0866',
 '089',
 '09',
 '0pl6xroabk',
 '10',
 '100',
 '1000',
 '1000xm3',
 '100gw',
 '100th',
 '104',
 '106',
 '107',
 '1073',
 '1080p',
 '1089',
 '109',
 '10pm',
 '11',
 '110',
 '110ps',
 '111',
 '112',
 '113',
 '1131',
 '114',
 '115',
 '115baa',
 '115bbda',
 '1165',
 '118',
 '119',
 '11th',
 '12',
 '120',
 '121',
 '1212',
 '122',
 '123',
 '1235163564865802240',
 '125',
 '127',
 '128',
 '128gb',
 '129',
 '12gb',
 '12mp',
 '12pm',
 '12th',
 '13',
 '130',
 '1300',
 '135',
 '136',
 '139',
 '13mp',
 '14',
 '140',
 '141',
 '142',
 '1428',
 '143',
 '1430',
 '1440p',
 '147',
 '149',
 '15',
 '150',
 '1500s',
 '151',
 '152',
 '153',
 '153a',
 '1545',
 '155',
 '156',
 '15th',
 '15w',
 '16',
 '160',
 '161',
 '166',
 '167',
 '1693',
 '16mp',
 '16th',
 '17',
 '1700',
 '171',
 '173nm',
 '175',
 '175gw',
 '1760s',
 '179',
 

In [12]:
len(LDA.components_)

7

In [13]:
type(LDA.components_)

numpy.ndarray

In [14]:
LDA.components_.shape

(7, 13263)

In [15]:
LDA.components_

array([[  1.32089198,  50.20404706,   0.14285714, ...,   1.14269543,
          0.14285714,   1.14285701],
       [  0.14285716,  13.56238016,   0.14285715, ...,   0.14285715,
          0.14285715,   0.14285717],
       [  0.14469968,   3.72399026,   0.14285715, ...,   0.14285715,
          0.14285715,   0.14285717],
       ...,
       [  0.14285715,  21.7977219 ,   1.14285713, ...,   0.14285715,
          0.14285715,   0.14285716],
       [  1.96297972, 107.94213583,   0.14285714, ...,   0.14301884,
          0.14309697,   0.14285715],
       [  0.14285715,   8.56746024,   0.14285715, ...,   0.14285715,
          0.14285715,   0.14285716]])

In [0]:
st = LDA.components_[0]

In [17]:
st.argsort()

array([11904,  4131,  4769, ..., 10432,  6162,  1579])

In [18]:
st.argsort()[-10:]

array([ 9680,  1585,  9678, 13190,  3343,  5534,  5384, 10432,  6162,
        1579])

In [0]:
tp = st.argsort()[-20:]

In [20]:
for i in tp :
  print(cv.get_feature_names()[i])  

indian
world
reserve
financial
impact
coronavirus
economy
economic
markets
central
rates
banks
rate
year
cut
growth
global
said
india
bank


#EXTRACT THE TOP 15 HIGH PROBABILTY WORDS FROM EACH TOPICS

In [21]:
for i,topic in enumerate(LDA.components_) :
  print(f"THE TOP 15 WORDS FOR TOPIC #{i}")
  print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['coronavirus', 'economy', 'economic', 'markets', 'central', 'rates', 'banks', 'rate', 'year', 'cut', 'growth', 'global', 'said', 'india', 'bank']




THE TOP 15 WORDS FOR TOPIC #1
['budget', 'energy', 'act', 'litre', 'power', 'year', 'time', 'government', 'companies', 'petrol', 'new', 'diesel', 'state', 'india', 'said']




THE TOP 15 WORDS FOR TOPIC #2
['cards', 'epfo', 'engines', 'rate', 'demand', 'aviation', 'delhi', 'pension', 'indian', 'sbi', 'crore', 'new', 'year', 'india', 'said']




THE TOP 15 WORDS FOR TOPIC #3
['speech', 'cci', 'virtual', 'google', 'services', 'flipkart', 'like', 'media', 'delhi', 'court', 'amazon', 'new', 'india', 'company', 'said']




THE TOP 15 WORDS FOR TOPIC #4
['capital', 'years', 'com', 'women', 'twitter', 'partner', '2020', 'director', 'crore', 'march', 'managing', 'livemint', 'said', 'india', 'says']




THE TOP 15 WORDS FOR TOPIC #5
['positive', 'countries', 'minister', 'delhi', 'government', 'new', 'covid', '19', 'c

#FINALLY ASSIGN THE HIGHEST TOPIC PROBABILTY TO EACH DOCUMENT

In [0]:
topic_results = LDA.transform(dtm)

In [23]:
topic_results[0].argmax()

0

In [0]:
data['topic'] = topic_results.argmax(axis=1)

In [0]:
data